server:
  port: 7070

spring:
  profiles:
    active: formatters
    include: plainFormatter, json-logs
  datasource:
    url: jdbc:h2:mem:testdb
    hikari:
      username: sa
      password: password
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    contexts: structure,dev,testdata
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true

#SERVER_PORT -> server.port
logging:
  level:
   root: INFO
   pl.effectivedev.articles: DEBUG
   org.hibernate: INFO
   org.hibernate.SQL: DEBUG
   org.hibernate.type.descriptor.sql: TRACE
   org.springframework.orm.jpa: DEBUG
   org.springframework.transaction: DEBUG

# /actuator/prometheus   <---- Prometheus  <--- Grafana

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,env,configprops,beans,info,scheduledtasks
  endpoint:
    health:
      # k8s readiness - aplikacja wsta?a i zainicjalizowa?a si?  /actuator/health/readiness
      # k8s liveness - /actuator/health/liveness
      # k8s startup - /actuator/health/readiness
      show-details: always
      probes:
        enabled: true
  health:
    ldap:
      enabled: false

# INFO_SOMETHING_JVM -> info.something.jvm
info: # /actuator/info
  version: 1.0.0
  something:
    other: "lorem"
    this: true
    home: ${HOME}
